[Greeter]
background=/usr/share/backgrounds/golden-gate.png
background-color=#000000
draw-user-backgrounds=false
draw-grid=false
theme-name=WhiteSur-Dark-solid
icon-theme-name=WhiteSur
cursor-theme-name=WhiteSur-cursors
cursor-theme-size=24
font-name=Inter 11
content-align=center
show-clock=true
clock-format=%-I:%M
show-hostname=false
show-a11y=false
show-keyboard=false
stretch-background-across-monitors=false
